import Head from 'next/head'
import Image from 'next/image'
import Layout from '../components/Layout'
import styles from '../styles/Home.module.css'
import AOS from 'aos';
import 'aos/dist/aos.css';
import "swiper/css/bundle";
import SwiperCore, { Autoplay } from 'swiper';

export default function Home() {
  return (
    <Layout >
      <div className="bg-black" >
        <Head>
          <title>Food ordering app</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
          
        </Head>


      </div>
    </Layout>
  )
}
 